// File generated by FlutterFire CLI.
// ignore_for_file: type=lint
import 'package:firebase_core/firebase_core.dart' show FirebaseOptions;
import 'package:flutter/foundation.dart'
    show defaultTargetPlatform, kIsWeb, TargetPlatform;

/// Default [FirebaseOptions] for use with your Firebase apps.
///
/// Example:
/// ```dart
/// import 'firebase_options.dart';
/// // ...
/// await Firebase.initializeApp(
///   options: DefaultFirebaseOptions.currentPlatform,
/// );
/// ```
class DefaultFirebaseOptions {
  static FirebaseOptions get currentPlatform {
    if (kIsWeb) {
      return web;
    }
    switch (defaultTargetPlatform) {
      case TargetPlatform.android:
        return android;
      case TargetPlatform.iOS:
        return ios;
      case TargetPlatform.macOS:
        return macos;
      case TargetPlatform.windows:
        return windows;
      case TargetPlatform.linux:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for linux - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      default:
        throw UnsupportedError(
          'DefaultFirebaseOptions are not supported for this platform.',
        );
    }
  }

  static const FirebaseOptions web = FirebaseOptions(
    apiKey: 'AIzaSyDro7tFSyqvaxfkyuQ7QYsAE6Ea7YihTz0',
    appId: '1:79901518732:web:fa6e6f055ead330b2704a9',
    messagingSenderId: '79901518732',
    projectId: 'property-management-3bfdf',
    authDomain: 'property-management-3bfdf.firebaseapp.com',
    storageBucket: 'property-management-3bfdf.appspot.com',
  );

  static const FirebaseOptions android = FirebaseOptions(
    apiKey: 'AIzaSyBXMhtkn__to9PEt4gae8E5h1jDg3ymQI8',
    appId: '1:79901518732:android:010e51418b819eef2704a9',
    messagingSenderId: '79901518732',
    projectId: 'property-management-3bfdf',
    storageBucket: 'property-management-3bfdf.appspot.com',
  );

  static const FirebaseOptions ios = FirebaseOptions(
    apiKey: 'AIzaSyD7ubdhw8ZJ5RlTgttTg0Gih6rWNnhxMDA',
    appId: '1:79901518732:ios:48824df69327594f2704a9',
    messagingSenderId: '79901518732',
    projectId: 'property-management-3bfdf',
    storageBucket: 'property-management-3bfdf.appspot.com',
    iosBundleId: 'com.example.propertyManagement',
  );

  static const FirebaseOptions macos = FirebaseOptions(
    apiKey: 'AIzaSyD7ubdhw8ZJ5RlTgttTg0Gih6rWNnhxMDA',
    appId: '1:79901518732:ios:48824df69327594f2704a9',
    messagingSenderId: '79901518732',
    projectId: 'property-management-3bfdf',
    storageBucket: 'property-management-3bfdf.appspot.com',
    iosBundleId: 'com.example.propertyManagement',
  );

  static const FirebaseOptions windows = FirebaseOptions(
    apiKey: 'AIzaSyDro7tFSyqvaxfkyuQ7QYsAE6Ea7YihTz0',
    appId: '1:79901518732:web:76aa6a78f6d888992704a9',
    messagingSenderId: '79901518732',
    projectId: 'property-management-3bfdf',
    authDomain: 'property-management-3bfdf.firebaseapp.com',
    storageBucket: 'property-management-3bfdf.appspot.com',
  );
}
